### ISSUE TITLE
ImportError: cannot import name 'LLMChain' from 'langchain.chains.question_answering'

### ISSUE THREAD

**Issue by WenshanL** [iii-org/akasha#2]
With a fresh install with 'pip install akasha-terminal', lanching "akasha ui" got following messages:
---
Traceback (most recent call last):
  File "/home/liou/miniconda3/envs/akasha/bin/akasha", line 5, in <module>
    from cli.glue import akasha
  File "/home/liou/miniconda3/envs/akasha/lib/python3.9/site-packages/cli/glue.py", line 3, in <module>
    import akasha as ak
  File "/home/liou/miniconda3/envs/akasha/lib/python3.9/site-packages/akasha/__init__.py", line 1, in <module>
    from .akasha import *
  File "/home/liou/miniconda3/envs/akasha/lib/python3.9/site-packages/akasha/akasha.py", line 5, in <module>
    from langchain.chains.question_answering import load_qa_chain, LLMChain
ImportError: cannot import name 'LLMChain' from 'langchain.chains.question_answering'
(/home/liou/miniconda3/envs/akasha/lib/python3.9/site-packages/langchain/chains/question_answering/__init__.py)
---
change the import line in akasha.py to 
from langchain.chains.question_answering import load_qa_chain
from langchain.chains import LLMChain

seems to fix the problem.
langchain version is the latest 0.1.20, may be an API version issue?

**Comment by tea9297** [comment]
LangChain changes its module names too frequently. In akasha 0.8.30, fix the LangChain installation version until it becomes stable.
