### ISSUE TITLE
akasha的文檔問答指令之相關問題

### ISSUE THREAD

**Issue by kaiSong113** [iii-org/akasha#5]
上禮拜測試akasha的文檔問答工具的時候，我在某幾個工具上遇到了一些問題，有一些修改完成了、有一些還沒成功修正錯誤，但我還是把全部都列在下方了。
（✅：已解決，❓：暫時解決，❌：未解決）

### 1. get_response 缺少輸出 ✅
這是get_response的範例程式碼：
```
import akasha

qa = akasha.Doc_QA(
verbose=False,
search_type="svm",
model="openai:gpt-3.5-turbo")

qa.get_response(
doc_path="docs/mic/",
prompt="五軸是甚麼?",
chunk_size=500,
max_doc_len=1500,
system_prompt="請用中文回答",
)
```
將它執行後，終端機沒有輸出任何東西。
後來發現是因為範例檔連print都沒有，所以將下半部做了一點簡單的修改後，就可以正常運作了：
```
response = qa.get_response(
doc_path="docs/mic/",
prompt="五軸是甚麼?",
chunk_size=500,
max_doc_len=1500,
system_prompt="請用中文回答",
)

print(response)
```

### 2. chain_of_thought的變數格式錯誤 ❓
這個工具的問題是出在模組裡的程式碼，錯誤訊息如下：

```
Traceback (most recent call last):
  File "/Users/kuoyukai/akasha2/test2.py", line 6, in <module>
    response = ak.chain_of_thought(dir_path, queries2, search_type='svm')
  File "/opt/anaconda3/envs/py3-8/lib/python3.8/site-packages/akasha/akashas.py", line 895, in chain_of_thought
    recursive_get_response(prompt_list)
  File "/opt/anaconda3/envs/py3-8/lib/python3.8/site-packages/akasha/akashas.py", line 870, in recursive_get_response
    helper.get_doc_length(self.language, self.prompt),
  File "/opt/anaconda3/envs/py3-8/lib/python3.8/site-packages/akasha/helper.py", line 333, in get_doc_length
    doc_length = len(list(jieba.cut(text)))
  File "/opt/anaconda3/envs/py3-8/lib/python3.8/site-packages/jieba/__init__.py", line 300, in cut
    sentence = strdecode(sentence)
  File "/opt/anaconda3/envs/py3-8/lib/python3.8/site-packages/jieba/_compat.py", line 79, in strdecode
    sentence = sentence.decode('utf-8')
AttributeError: 'list' object has no attribute 'decode'
```

進入到akashas.py中查看後，我擷取了幾行主要造成錯誤的程式碼：
```
self.prompt = [] #line845
def recursive_get_response(prompt_list): #line851
    for prompt in prompt_list: #line853
        self.prompt.append(prompt) #line858
        helper.get_doc_length(self.language, self.prompt) #line870
```
由於line845的self.prompt是list的格式，把它當作line870的函式helper.get_doc_length的輸入後，一層一層進到_compat.py的函式decode時：
`sentence = sentence.decode('gbk', 'ignore')`
就出現了sentence的格式為list而導致的錯誤，因此我嘗試在上方造成錯誤的程式碼中加入了兩個小修改：
`index = 0`
`helper.get_doc_length(self.language, self.prompt[index])`
最後變成：
```
self.prompt = []
def recursive_get_response(prompt_list):
    index = 0
    for prompt in prompt_list:
        self.prompt.append(prompt)
        helper.get_doc_length(self.language, self.prompt[index])
```
修改後self.prompt[index]變成str的格式，就成功跑出輸出內容了，只是**格式跟範例輸出有點不一樣**。
這是範例的輸出格式：
```
response 1:
西門子自有工廠朝工業4.0發展的方式包括以下幾個方面：

1. 數位化戰略：西門子提出數位化戰略，從工業4.0策略擬定到落地執行，為客戶提供一條龍服務。他們設計數位工廠原型
，搭配OT、IT方案，並使用西門子的MindSphere工業物聯網平台，發展數據可視化和數據分析相關應用。

2. 跨領域合作：西門子近年積極與雲服務商、系統商等跨領域合作，推動智慧製造解決方案。此外，他們也與SAP進行ERP整合，專注於物聯網領域。

3. 虛實整合：西門子在中國大陸成都生產研發基地的案例中，從研發、生產、訂單管理、供應商管理到物流作業
，實現了整條價值鏈的虛實整合。他們不斷提高配料、傳輸、檢測等流程的自動化程度。

總體而言，西門子通過數位化戰略、跨領域合作和虛實整合等方式，推動自有工廠朝工業4.0發 
展。他們致力於提升生產效率和效能，並利用先進的技術和解決方案實現智慧工廠的建設。






response 2:
「工業4.0成熟度指數」的發展路徑劃分為六個成熟度，分別是電腦化、可連結、可視化、可分析、可預測和自適應。

1. 電腦化：這是工業4.0發展的起點，指企業開始使用計算機技
術，人員不再手動操作機械。然而，機械仍未聯網，各個IT系統仍各自獨立，資料尚未串聯。例如，企業的ERP系統與生產相關的系統獨立運作，訂單與產品品檢紀錄分散於兩套系統，導致 
訂單無法回溯出現品質問題的環節。

2. 可連結：在這個成熟度階段，企業開始將各個IT系統進行連接，實現資料的串聯。這使得不同系統之間可以共享資料，提高資訊的流通效率。例 
如，企業的ERP系統與生產相關的系統進行連接，訂單與產品品檢紀錄可以實現資料的回溯。

3. 可視化：在這個成熟度階段，企業開始實現資料的可視化，將資料以圖形化或圖表化的方
式呈現，使得管理者可以直觀地了解企業的運營狀況。例如，企業可以使用數據儀表板或報表來呈現生產線的運行情況和產品的品質指標。

4. 可分析：在這個成熟度階段，企業開始進 
行資料的分析，利用數據分析工具和算法來挖掘資料中的價值和洞察。這使得企業可以更深入地了解生產過程中的問題和潛在的改進空間。例如，企業可以使用數據分析工具來分析生產線的
效率和品質問題，並提出改進措施。

5. 可預測：在這個成熟度階段，企業開始利用資料分析的結果來進行預測和預測模型的建立。這使得企業可以預測生產過程中可能出現的問題，並 
提前採取相應的措施。例如，企業可以利用預測模型來預測生產線的故障和產品的品質問題，並提前進行維護和調整。

6. 自適應：在這個成熟度階段，企業開始實現自動化和自適應能 
力，使得生產過程可以根據實時的數據和環境變化進行調整和優化。這使得企業可以更靈活地應對市場需求和生產變化。例如，企業可以實現生產線的自動調整和產品的自動優化，以適應市
場需求的變化。

這六個成熟度階段代表了企業在工業4.0發展過程中的不同階段和能力水平，企業可以根據自身的情況和目標，逐步提升成熟度，實現工業4.0的目標。






response 3:
根據西門子自有工廠朝工業4.0發展的方式，可以探討其在工業4.0成熟度指標中的幾個方面：

 

1. 數位化戰略：西門子提出數位化戰略，從工業4.0策略擬定到落地執行提供一條龍服務
。這代表企業在工業4.0成熟度指標中已經達到了可連結和可視化的階段，並開始將數據應用於生產優化和資源利用。

 

2. 整合系統：西門子在廠內進行軟體間整合，包括PLM、ERP、MOM 
、WMS和Automation五大系統的整合，使數據互聯互通。這代表企業在工業4.0成熟度指標中已經達到了可分析和可預測的階段，並能夠利用數據分析技術進行深入分析和預測。

 

3. 數據 應用：西門子利用自有的數位雙生軟體Tecnomatix，打造虛擬工廠，模擬生產狀況或監控實際生產狀況。這代表企業在工業4.0成熟度指標中已經達到了可分析和可預測的階段，並能夠利用 
數據應用提供的資訊，優化生產設備和工序。

 

總的來說，根據西門子自有工廠朝工業4.0發展的方式，可以看出他們在工業4.0成熟度指標中已經達到了可連結、可視化、可分析和可預測，優化生產設備和工序。
```
而我的問題跟檔案雖然都不一樣，但輸出的內容格式大概是這樣子：

`['張儀是戰國時期的一位著名政治家和軍事家，他是魏國的重要人物，也是著名的諸子百家思想家之一。', '李斯是戰國時期楚國上蔡（今河南省上蔡縣）人，他是一位著名的政治家和諸子百家思想家之一。他曾在秦朝擔任丞相，提出了一系列改革建議，包括廢除封建制度、統一郡縣、焚燒百家書等。他也是一位優秀的文學家和書法家。', '諫逐客書是李斯上呈秦王的奏疏，力陳驅逐客卿之不當。全文勸諫秦王欲富國強兵、統一天下，必須不分地域，廣攬人才。全文有理有據，善於鋪陳，文筆縱橫跌宕，句式駢散並用，長短相間，詞藻華麗，節奏明快，與精闢的論點相得益彰。']`
（檔案：[chinese.txt](https://github.com/user-attachments/files/16330091/chinese.txt)）

感覺格式跟範例差有點多，但也不知道要該怎麼修改。
### 3. ask_agent的變數格式錯誤 ❌
這個工具的問題也是出在模組裡的程式碼，錯誤訊息如下：
```
selected openai model gpt-35-turbo.

selected openai embeddings.

```json
{
        "need": "1",
        "follow_up": [
                "LPWAN是什么?",
                "5G是什么?"
        ]
}
```LPWAN是一种低功耗广域网络，专门用于连接低功耗设备，覆盖范围较广，但传输速率较低。而5G是第五代移动通信技术，具有更高的传输速率和更低的延迟，适用于连接大量设备和实现高速数据传输。LPWAN主要用于物联网设备的连接，而5G则是更为通用的移动通信技术。Traceback (most recent call last):
  File "/Users/kuoyukai/akasha2/test5.py", line 8, in <module>
    res = ak.ask_agent(
  File "/opt/anaconda3/envs/py3-8/lib/python3.8/site-packages/akasha/akashas.py", line 1200, in ask_agent
    parse_json = akasha.helper.extract_json(ret)
  File "/opt/anaconda3/envs/py3-8/lib/python3.8/site-packages/akasha/helper.py", line 440, in extract_json
    s = match.group()
AttributeError: 'NoneType' object has no attribute 'group'
```
前面其實還有輸出一些東西，但到後面就突然卡住了，因此我翻出了錯誤訊息中提到的函式extract_json：
```
def extract_json(s: str) -> Union[dict, None]:
    # Use a regular expression to find the JSON part of the string
    match = re.search(r'\{.*\}', s, re.DOTALL)
    stack = []
    start = 0
    s = match.group()
```
還有進入此函式的程式碼：
```
ret = self.ask_self(prompt=prod_prompt, system_prompt=prod_sys_prompt)
parse_json = akasha.helper.extract_json(ret)
```
變數ret中似乎沒有包含 '{}' 的字串，導致進入函式extract_json後，函式search回傳了None，最後函式group也因此出現錯誤。
但由於我找不太到哪篇程式碼有影響到{}的產生，因此最後沒有成功解決問題。

### 4.ask_self輸出了兩次 ❌
我執行了範例的程式碼，而輸出結果如下：
```
selected openai model gpt-4.

selected openai embeddings.

langchain的套件版本是0.1.0以上。根据您提供的信息，langchain的套件版本应该是0.1.0或者更高版本。% 
```
而範例輸出只有後面那一段，所以我檢查了一下內部的程式碼，找出了兩個似乎產生了輸出的位置：
```
#first
batch_responses = helper.call_batch_model(
    self.model_obj, [prompt] * len(cur_documents), prod_sys_prompts)

#second
self.response = helper.call_model(
    self.model_obj, "\n\n".join(batch_responses),
    prompts.default_conclusion_prompt(prompt, self.language))
```
但由於我進入函式的定義之後都看不太懂，所以最後沒有找到解決辦法。

以上是我在測試akasha文檔問答指令時遇到的一些小問題，希望這些資訊能讓此工具更加完善。

**Comment by YCHM0304** [comment]
# chain_of_thought的變數格式錯誤 修改
```python
def recursive_get_response(prompt_list):
      pre_result = []
      for prompt in prompt_list:
              if isinstance(prompt, list):
                      response = recursive_get_response(prompt)
                      pre_result.append(Document(page_content="".join(response)))
              else:
                      self.prompt.append(prompt)
                      docs, docs_len, tokens = search.get_docs(
                              self.db,
                              self.embeddings_obj,
                              retrivers_list,
                              prompt,
                              self.use_rerank,
                              self.language,
                              self.search_type,
                              self.verbose,
                              self.model_obj,
                              self.max_doc_len -
                              helper.get_doc_length(self.language, self.prompt),    #這裡使用self.prompt
                              compression=self.compression,
                      )
```
<br/>
因為 `helper.get_doc_length(self.language, self.prompt)` 中的 `self.prompt`是list，而要輸入的應該是for迴圈當前的prompt，所以修改成 `helper.get_doc_length(self.language, prompt)` 就可以正常執行了。
> [!NOTE]  
> 格式輸出問題尚未解決。

**Comment by tea9297** [comment]
Issue 1
 You can either set verbose=True  or print the response to get the stdout.
 
 Issue 2 
 Yeah, self.prompt should be list in the chain_of_thought, so we should join the list into string to calculate the total length.
 The return value of the `chain_of_thought` function is a list; the output in the README is just for display purposes."
 
 Issue 3 & 4
Fix the unintented behavior of calling model two times in ask_self when the info texts not exceed max_doc_len. We should only call model multiple times to merge answers when there's too many info.

The error in issue 3 is because of the duplicate calling of ask_self, just in case, we add the check None in extract_json to avoid the error when parsing json from response.
 
 
 The above issues fixed in akasha-terminal=0.8.52
